changelog:
  exclude:
    labels:
      - ignore-for-release
      - internal
    authors:
      - dependabot[bot]
  categories:
    - title: "🚀 New for users"
      labels:
        - enhancement
        - user-facing
    - title: "🐛 Fixes"
      labels:
        - bug
        - fix
    - title: "🔒 Security and privacy"
      labels:
        - security
        - privacy
    - title: "⚙️ Maintenance"
      labels:
        - maintenance
        - dependencies
        - ci
    - title: "📦 Other changes"
      labels:
        - "*"
